//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 09:06:12 AM BRT 
//


package br.com.cmabreu.webomt.ieee1516e;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for capabilityEnumerations.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="capabilityEnumerations">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Register"/>
 *     &lt;enumeration value="Achieve"/>
 *     &lt;enumeration value="RegisterAchieve"/>
 *     &lt;enumeration value="NoSynch"/>
 *     &lt;enumeration value="NA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "capabilityEnumerations")
@XmlEnum
public enum CapabilityEnumerations {

    @XmlEnumValue("Register")
    REGISTER("Register"),
    @XmlEnumValue("Achieve")
    ACHIEVE("Achieve"),
    @XmlEnumValue("RegisterAchieve")
    REGISTER_ACHIEVE("RegisterAchieve"),
    @XmlEnumValue("NoSynch")
    NO_SYNCH("NoSynch"),
    NA("NA");
    private final java.lang.String value;

    CapabilityEnumerations(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static CapabilityEnumerations fromValue(java.lang.String v) {
        for (CapabilityEnumerations c: CapabilityEnumerations.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
