//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 09:06:12 AM BRT 
//


package br.com.cmabreu.webomt.ieee1516e;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for dataTypesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataTypesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="basicDataRepresentations" type="{http://standards.ieee.org/IEEE1516-2010}basicDataRepresentationsType" minOccurs="0"/>
 *         &lt;element name="simpleDataTypes" type="{http://standards.ieee.org/IEEE1516-2010}simpleDataTypesType" minOccurs="0"/>
 *         &lt;element name="enumeratedDataTypes" type="{http://standards.ieee.org/IEEE1516-2010}enumeratedDataTypesType" minOccurs="0"/>
 *         &lt;element name="arrayDataTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://standards.ieee.org/IEEE1516-2010}arrayDataTypesType">
 *                 &lt;anyAttribute namespace='##other'/>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fixedRecordDataTypes" type="{http://standards.ieee.org/IEEE1516-2010}fixedRecordDataTypesType" minOccurs="0"/>
 *         &lt;element name="variantRecordDataTypes" type="{http://standards.ieee.org/IEEE1516-2010}variantRecordDataTypesType" minOccurs="0"/>
 *         &lt;any namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://standards.ieee.org/IEEE1516-2010}commonAttributes"/>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataTypesType", propOrder = {
    "basicDataRepresentations",
    "simpleDataTypes",
    "enumeratedDataTypes",
    "arrayDataTypes",
    "fixedRecordDataTypes",
    "variantRecordDataTypes",
    "any"
})
public class DataTypesType {

    protected BasicDataRepresentationsType basicDataRepresentations;
    protected SimpleDataTypesType simpleDataTypes;
    protected EnumeratedDataTypesType enumeratedDataTypes;
    protected DataTypesType.ArrayDataTypes arrayDataTypes;
    protected FixedRecordDataTypesType fixedRecordDataTypes;
    protected VariantRecordDataTypesType variantRecordDataTypes;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(name = "idtag")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String idtag;
    @XmlAnyAttribute
    private Map<QName, java.lang.String> otherAttributes = new HashMap<QName, java.lang.String>();

    /**
     * Gets the value of the basicDataRepresentations property.
     * 
     * @return
     *     possible object is
     *     {@link BasicDataRepresentationsType }
     *     
     */
    public BasicDataRepresentationsType getBasicDataRepresentations() {
        return basicDataRepresentations;
    }

    /**
     * Sets the value of the basicDataRepresentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicDataRepresentationsType }
     *     
     */
    public void setBasicDataRepresentations(BasicDataRepresentationsType value) {
        this.basicDataRepresentations = value;
    }

    /**
     * Gets the value of the simpleDataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleDataTypesType }
     *     
     */
    public SimpleDataTypesType getSimpleDataTypes() {
        return simpleDataTypes;
    }

    /**
     * Sets the value of the simpleDataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleDataTypesType }
     *     
     */
    public void setSimpleDataTypes(SimpleDataTypesType value) {
        this.simpleDataTypes = value;
    }

    /**
     * Gets the value of the enumeratedDataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link EnumeratedDataTypesType }
     *     
     */
    public EnumeratedDataTypesType getEnumeratedDataTypes() {
        return enumeratedDataTypes;
    }

    /**
     * Sets the value of the enumeratedDataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumeratedDataTypesType }
     *     
     */
    public void setEnumeratedDataTypes(EnumeratedDataTypesType value) {
        this.enumeratedDataTypes = value;
    }

    /**
     * Gets the value of the arrayDataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypesType.ArrayDataTypes }
     *     
     */
    public DataTypesType.ArrayDataTypes getArrayDataTypes() {
        return arrayDataTypes;
    }

    /**
     * Sets the value of the arrayDataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypesType.ArrayDataTypes }
     *     
     */
    public void setArrayDataTypes(DataTypesType.ArrayDataTypes value) {
        this.arrayDataTypes = value;
    }

    /**
     * Gets the value of the fixedRecordDataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link FixedRecordDataTypesType }
     *     
     */
    public FixedRecordDataTypesType getFixedRecordDataTypes() {
        return fixedRecordDataTypes;
    }

    /**
     * Sets the value of the fixedRecordDataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedRecordDataTypesType }
     *     
     */
    public void setFixedRecordDataTypes(FixedRecordDataTypesType value) {
        this.fixedRecordDataTypes = value;
    }

    /**
     * Gets the value of the variantRecordDataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link VariantRecordDataTypesType }
     *     
     */
    public VariantRecordDataTypesType getVariantRecordDataTypes() {
        return variantRecordDataTypes;
    }

    /**
     * Sets the value of the variantRecordDataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantRecordDataTypesType }
     *     
     */
    public void setVariantRecordDataTypes(VariantRecordDataTypesType value) {
        this.variantRecordDataTypes = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the idtag property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIdtag() {
        return idtag;
    }

    /**
     * Sets the value of the idtag property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIdtag(java.lang.String value) {
        this.idtag = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, java.lang.String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://standards.ieee.org/IEEE1516-2010}arrayDataTypesType">
     *       &lt;anyAttribute namespace='##other'/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ArrayDataTypes
        extends ArrayDataTypesType
    {


    }

}
