//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 09:06:12 AM BRT 
//


package br.com.cmabreu.webomt.ieee1516e;

import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for objectModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="objectModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modelIdentification" type="{http://standards.ieee.org/IEEE1516-2010}modelIdentificationType" minOccurs="0"/>
 *         &lt;element name="serviceUtilization" type="{http://standards.ieee.org/IEEE1516-2010}serviceUtilizationType" minOccurs="0"/>
 *         &lt;element name="objects" type="{http://standards.ieee.org/IEEE1516-2010}objectsType" minOccurs="0"/>
 *         &lt;element name="interactions" type="{http://standards.ieee.org/IEEE1516-2010}interactionsType" minOccurs="0"/>
 *         &lt;element name="dimensions" type="{http://standards.ieee.org/IEEE1516-2010}dimensionsType" minOccurs="0"/>
 *         &lt;element name="time" type="{http://standards.ieee.org/IEEE1516-2010}timeType" minOccurs="0"/>
 *         &lt;element name="tags" type="{http://standards.ieee.org/IEEE1516-2010}tagsType" minOccurs="0"/>
 *         &lt;element name="synchronizations" type="{http://standards.ieee.org/IEEE1516-2010}synchronizationsType" minOccurs="0"/>
 *         &lt;element name="transportations" type="{http://standards.ieee.org/IEEE1516-2010}transportationsType" minOccurs="0"/>
 *         &lt;element name="switches" type="{http://standards.ieee.org/IEEE1516-2010}switchesType" minOccurs="0"/>
 *         &lt;element name="updateRates" type="{http://standards.ieee.org/IEEE1516-2010}updateRatesType" minOccurs="0"/>
 *         &lt;element name="dataTypes" type="{http://standards.ieee.org/IEEE1516-2010}dataTypesType" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://standards.ieee.org/IEEE1516-2010}notesType" minOccurs="0"/>
 *         &lt;any namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://standards.ieee.org/IEEE1516-2010}commonAttributes"/>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectModelType", propOrder = {
    "modelIdentification",
    "serviceUtilization",
    "objects",
    "interactions",
    "dimensions",
    "time",
    "tags",
    "synchronizations",
    "transportations",
    "switches",
    "updateRates",
    "dataTypes",
    "notes",
    "any"
})
public class ObjectModelType {

    protected ModelIdentificationType modelIdentification;
    protected ServiceUtilizationType serviceUtilization;
    protected ObjectsType objects;
    protected InteractionsType interactions;
    protected DimensionsType dimensions;
    protected TimeType time;
    protected TagsType tags;
    protected SynchronizationsType synchronizations;
    protected TransportationsType transportations;
    protected SwitchesType switches;
    protected UpdateRatesType updateRates;
    protected DataTypesType dataTypes;
    protected NotesType notes;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(name = "idtag")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String idtag;
    @XmlAnyAttribute
    private Map<QName, java.lang.String> otherAttributes = new HashMap<QName, java.lang.String>();

    /**
     * Gets the value of the modelIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ModelIdentificationType }
     *     
     */
    public ModelIdentificationType getModelIdentification() {
        return modelIdentification;
    }

    /**
     * Sets the value of the modelIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelIdentificationType }
     *     
     */
    public void setModelIdentification(ModelIdentificationType value) {
        this.modelIdentification = value;
    }

    /**
     * Gets the value of the serviceUtilization property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceUtilizationType }
     *     
     */
    public ServiceUtilizationType getServiceUtilization() {
        return serviceUtilization;
    }

    /**
     * Sets the value of the serviceUtilization property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceUtilizationType }
     *     
     */
    public void setServiceUtilization(ServiceUtilizationType value) {
        this.serviceUtilization = value;
    }

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectsType }
     *     
     */
    public ObjectsType getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectsType }
     *     
     */
    public void setObjects(ObjectsType value) {
        this.objects = value;
    }

    /**
     * Gets the value of the interactions property.
     * 
     * @return
     *     possible object is
     *     {@link InteractionsType }
     *     
     */
    public InteractionsType getInteractions() {
        return interactions;
    }

    /**
     * Sets the value of the interactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteractionsType }
     *     
     */
    public void setInteractions(InteractionsType value) {
        this.interactions = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionsType }
     *     
     */
    public DimensionsType getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionsType }
     *     
     */
    public void setDimensions(DimensionsType value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link TimeType }
     *     
     */
    public TimeType getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeType }
     *     
     */
    public void setTime(TimeType value) {
        this.time = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link TagsType }
     *     
     */
    public TagsType getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagsType }
     *     
     */
    public void setTags(TagsType value) {
        this.tags = value;
    }

    /**
     * Gets the value of the synchronizations property.
     * 
     * @return
     *     possible object is
     *     {@link SynchronizationsType }
     *     
     */
    public SynchronizationsType getSynchronizations() {
        return synchronizations;
    }

    /**
     * Sets the value of the synchronizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynchronizationsType }
     *     
     */
    public void setSynchronizations(SynchronizationsType value) {
        this.synchronizations = value;
    }

    /**
     * Gets the value of the transportations property.
     * 
     * @return
     *     possible object is
     *     {@link TransportationsType }
     *     
     */
    public TransportationsType getTransportations() {
        return transportations;
    }

    /**
     * Sets the value of the transportations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportationsType }
     *     
     */
    public void setTransportations(TransportationsType value) {
        this.transportations = value;
    }

    /**
     * Gets the value of the switches property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchesType }
     *     
     */
    public SwitchesType getSwitches() {
        return switches;
    }

    /**
     * Sets the value of the switches property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchesType }
     *     
     */
    public void setSwitches(SwitchesType value) {
        this.switches = value;
    }

    /**
     * Gets the value of the updateRates property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateRatesType }
     *     
     */
    public UpdateRatesType getUpdateRates() {
        return updateRates;
    }

    /**
     * Sets the value of the updateRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateRatesType }
     *     
     */
    public void setUpdateRates(UpdateRatesType value) {
        this.updateRates = value;
    }

    /**
     * Gets the value of the dataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypesType }
     *     
     */
    public DataTypesType getDataTypes() {
        return dataTypes;
    }

    /**
     * Sets the value of the dataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypesType }
     *     
     */
    public void setDataTypes(DataTypesType value) {
        this.dataTypes = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link NotesType }
     *     
     */
    public NotesType getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotesType }
     *     
     */
    public void setNotes(NotesType value) {
        this.notes = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the idtag property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIdtag() {
        return idtag;
    }

    /**
     * Sets the value of the idtag property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIdtag(java.lang.String value) {
        this.idtag = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, java.lang.String> getOtherAttributes() {
        return otherAttributes;
    }

}
