//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 09:06:12 AM BRT 
//


package br.com.cmabreu.webomt.ieee1516e;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ieee1516e package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObjectModel_QNAME = new QName("http://standards.ieee.org/IEEE1516-2010", "objectModel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ieee1516e
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InteractionClassType }
     * 
     */
    public InteractionClassType createInteractionClassType() {
        return new InteractionClassType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link FixedRecordDataType }
     * 
     */
    public FixedRecordDataType createFixedRecordDataType() {
        return new FixedRecordDataType();
    }

    /**
     * Create an instance of {@link SynchronizationsType }
     * 
     */
    public SynchronizationsType createSynchronizationsType() {
        return new SynchronizationsType();
    }

    /**
     * Create an instance of {@link EnumeratedDataTypesType }
     * 
     */
    public EnumeratedDataTypesType createEnumeratedDataTypesType() {
        return new EnumeratedDataTypesType();
    }

    /**
     * Create an instance of {@link EnumeratedDataType }
     * 
     */
    public EnumeratedDataType createEnumeratedDataType() {
        return new EnumeratedDataType();
    }

    /**
     * Create an instance of {@link FixedRecordDataTypesType }
     * 
     */
    public FixedRecordDataTypesType createFixedRecordDataTypesType() {
        return new FixedRecordDataTypesType();
    }

    /**
     * Create an instance of {@link DimensionType }
     * 
     */
    public DimensionType createDimensionType() {
        return new DimensionType();
    }

    /**
     * Create an instance of {@link DataTypesType }
     * 
     */
    public DataTypesType createDataTypesType() {
        return new DataTypesType();
    }

    /**
     * Create an instance of {@link ArrayDataTypesType }
     * 
     */
    public ArrayDataTypesType createArrayDataTypesType() {
        return new ArrayDataTypesType();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType }
     * 
     */
    public ServiceUtilizationType createServiceUtilizationType() {
        return new ServiceUtilizationType();
    }

    /**
     * Create an instance of {@link SimpleDataTypesType }
     * 
     */
    public SimpleDataTypesType createSimpleDataTypesType() {
        return new SimpleDataTypesType();
    }

    /**
     * Create an instance of {@link IdReferenceType }
     * 
     */
    public IdReferenceType createIdReferenceType() {
        return new IdReferenceType();
    }

    /**
     * Create an instance of {@link BasicDataRepresentationsType }
     * 
     */
    public BasicDataRepresentationsType createBasicDataRepresentationsType() {
        return new BasicDataRepresentationsType();
    }

    /**
     * Create an instance of {@link TransportationType }
     * 
     */
    public TransportationType createTransportationType() {
        return new TransportationType();
    }

    /**
     * Create an instance of {@link VariantRecordDataType }
     * 
     */
    public VariantRecordDataType createVariantRecordDataType() {
        return new VariantRecordDataType();
    }

    /**
     * Create an instance of {@link NotesType }
     * 
     */
    public NotesType createNotesType() {
        return new NotesType();
    }

    /**
     * Create an instance of {@link ModelIdentificationType }
     * 
     */
    public ModelIdentificationType createModelIdentificationType() {
        return new ModelIdentificationType();
    }

    /**
     * Create an instance of {@link TransportationsType }
     * 
     */
    public TransportationsType createTransportationsType() {
        return new TransportationsType();
    }

    /**
     * Create an instance of {@link VariantRecordDataTypesType }
     * 
     */
    public VariantRecordDataTypesType createVariantRecordDataTypesType() {
        return new VariantRecordDataTypesType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link DimensionsType }
     * 
     */
    public DimensionsType createDimensionsType() {
        return new DimensionsType();
    }

    /**
     * Create an instance of {@link InteractionClass }
     * 
     */
    public InteractionClass createInteractionClass() {
        return new InteractionClass();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link SharingType }
     * 
     */
    public SharingType createSharingType() {
        return new SharingType();
    }

    /**
     * Create an instance of {@link InteractionClassType.Dimensions }
     * 
     */
    public InteractionClassType.Dimensions createInteractionClassTypeDimensions() {
        return new InteractionClassType.Dimensions();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link ObjectModelType }
     * 
     */
    public ObjectModelType createObjectModelType() {
        return new ObjectModelType();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link UpdateType }
     * 
     */
    public UpdateType createUpdateType() {
        return new UpdateType();
    }

    /**
     * Create an instance of {@link OwnershipType }
     * 
     */
    public OwnershipType createOwnershipType() {
        return new OwnershipType();
    }

    /**
     * Create an instance of {@link AttributeType.Dimensions }
     * 
     */
    public AttributeType.Dimensions createAttributeTypeDimensions() {
        return new AttributeType.Dimensions();
    }

    /**
     * Create an instance of {@link ObjectClass }
     * 
     */
    public ObjectClass createObjectClass() {
        return new ObjectClass();
    }

    /**
     * Create an instance of {@link ObjectClassType }
     * 
     */
    public ObjectClassType createObjectClassType() {
        return new ObjectClassType();
    }

    /**
     * Create an instance of {@link ArrayDatatypeEncodingType }
     * 
     */
    public ArrayDatatypeEncodingType createArrayDatatypeEncodingType() {
        return new ArrayDatatypeEncodingType();
    }

    /**
     * Create an instance of {@link ArrayDataType }
     * 
     */
    public ArrayDataType createArrayDataType() {
        return new ArrayDataType();
    }

    /**
     * Create an instance of {@link CapabilityType }
     * 
     */
    public CapabilityType createCapabilityType() {
        return new CapabilityType();
    }

    /**
     * Create an instance of {@link UpdateRateType }
     * 
     */
    public UpdateRateType createUpdateRateType() {
        return new UpdateRateType();
    }

    /**
     * Create an instance of {@link BasicDataType }
     * 
     */
    public BasicDataType createBasicDataType() {
        return new BasicDataType();
    }

    /**
     * Create an instance of {@link TagsType }
     * 
     */
    public TagsType createTagsType() {
        return new TagsType();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link PocTypeType }
     * 
     */
    public PocTypeType createPocTypeType() {
        return new PocTypeType();
    }

    /**
     * Create an instance of {@link RateType }
     * 
     */
    public RateType createRateType() {
        return new RateType();
    }

    /**
     * Create an instance of {@link UpdateRatesType }
     * 
     */
    public UpdateRatesType createUpdateRatesType() {
        return new UpdateRatesType();
    }

    /**
     * Create an instance of {@link CardinalityType }
     * 
     */
    public CardinalityType createCardinalityType() {
        return new CardinalityType();
    }

    /**
     * Create an instance of {@link ObjectsType }
     * 
     */
    public ObjectsType createObjectsType() {
        return new ObjectsType();
    }

    /**
     * Create an instance of {@link Size }
     * 
     */
    public Size createSize() {
        return new Size();
    }

    /**
     * Create an instance of {@link SecurityClassificationType }
     * 
     */
    public SecurityClassificationType createSecurityClassificationType() {
        return new SecurityClassificationType();
    }

    /**
     * Create an instance of {@link SynchronizationPointType }
     * 
     */
    public SynchronizationPointType createSynchronizationPointType() {
        return new SynchronizationPointType();
    }

    /**
     * Create an instance of {@link SwitchType }
     * 
     */
    public SwitchType createSwitchType() {
        return new SwitchType();
    }

    /**
     * Create an instance of {@link GlyphType }
     * 
     */
    public GlyphType createGlyphType() {
        return new GlyphType();
    }

    /**
     * Create an instance of {@link FixedRecordEncodingType }
     * 
     */
    public FixedRecordEncodingType createFixedRecordEncodingType() {
        return new FixedRecordEncodingType();
    }

    /**
     * Create an instance of {@link ResignSwitchType }
     * 
     */
    public ResignSwitchType createResignSwitchType() {
        return new ResignSwitchType();
    }

    /**
     * Create an instance of {@link EndianType }
     * 
     */
    public EndianType createEndianType() {
        return new EndianType();
    }

    /**
     * Create an instance of {@link VariantRecordEncodingType }
     * 
     */
    public VariantRecordEncodingType createVariantRecordEncodingType() {
        return new VariantRecordEncodingType();
    }

    /**
     * Create an instance of {@link InteractionsType }
     * 
     */
    public InteractionsType createInteractionsType() {
        return new InteractionsType();
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link PocType }
     * 
     */
    public PocType createPocType() {
        return new PocType();
    }

    /**
     * Create an instance of {@link NonEmptyString }
     * 
     */
    public NonEmptyString createNonEmptyString() {
        return new NonEmptyString();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link SimpleDataType }
     * 
     */
    public SimpleDataType createSimpleDataType() {
        return new SimpleDataType();
    }

    /**
     * Create an instance of {@link ApplicationDomainType }
     * 
     */
    public ApplicationDomainType createApplicationDomainType() {
        return new ApplicationDomainType();
    }

    /**
     * Create an instance of {@link SwitchesType }
     * 
     */
    public SwitchesType createSwitchesType() {
        return new SwitchesType();
    }

    /**
     * Create an instance of {@link FixedRecordDataType.Field }
     * 
     */
    public FixedRecordDataType.Field createFixedRecordDataTypeField() {
        return new FixedRecordDataType.Field();
    }

    /**
     * Create an instance of {@link SynchronizationsType.SynchronizationPoint }
     * 
     */
    public SynchronizationsType.SynchronizationPoint createSynchronizationsTypeSynchronizationPoint() {
        return new SynchronizationsType.SynchronizationPoint();
    }

    /**
     * Create an instance of {@link EnumeratedDataTypesType.EnumeratedData }
     * 
     */
    public EnumeratedDataTypesType.EnumeratedData createEnumeratedDataTypesTypeEnumeratedData() {
        return new EnumeratedDataTypesType.EnumeratedData();
    }

    /**
     * Create an instance of {@link EnumeratedDataType.Enumerator }
     * 
     */
    public EnumeratedDataType.Enumerator createEnumeratedDataTypeEnumerator() {
        return new EnumeratedDataType.Enumerator();
    }

    /**
     * Create an instance of {@link FixedRecordDataTypesType.FixedRecordData }
     * 
     */
    public FixedRecordDataTypesType.FixedRecordData createFixedRecordDataTypesTypeFixedRecordData() {
        return new FixedRecordDataTypesType.FixedRecordData();
    }

    /**
     * Create an instance of {@link DimensionType.UpperBound }
     * 
     */
    public DimensionType.UpperBound createDimensionTypeUpperBound() {
        return new DimensionType.UpperBound();
    }

    /**
     * Create an instance of {@link DimensionType.Value }
     * 
     */
    public DimensionType.Value createDimensionTypeValue() {
        return new DimensionType.Value();
    }

    /**
     * Create an instance of {@link DataTypesType.ArrayDataTypes }
     * 
     */
    public DataTypesType.ArrayDataTypes createDataTypesTypeArrayDataTypes() {
        return new DataTypesType.ArrayDataTypes();
    }

    /**
     * Create an instance of {@link ArrayDataTypesType.ArrayData }
     * 
     */
    public ArrayDataTypesType.ArrayData createArrayDataTypesTypeArrayData() {
        return new ArrayDataTypesType.ArrayData();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.Connect }
     * 
     */
    public ServiceUtilizationType.Connect createServiceUtilizationTypeConnect() {
        return new ServiceUtilizationType.Connect();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.Disconnect }
     * 
     */
    public ServiceUtilizationType.Disconnect createServiceUtilizationTypeDisconnect() {
        return new ServiceUtilizationType.Disconnect();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ConnectionLost }
     * 
     */
    public ServiceUtilizationType.ConnectionLost createServiceUtilizationTypeConnectionLost() {
        return new ServiceUtilizationType.ConnectionLost();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.CreateFederationExecution }
     * 
     */
    public ServiceUtilizationType.CreateFederationExecution createServiceUtilizationTypeCreateFederationExecution() {
        return new ServiceUtilizationType.CreateFederationExecution();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DestroyFederationExecution }
     * 
     */
    public ServiceUtilizationType.DestroyFederationExecution createServiceUtilizationTypeDestroyFederationExecution() {
        return new ServiceUtilizationType.DestroyFederationExecution();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ListFederationExecutions }
     * 
     */
    public ServiceUtilizationType.ListFederationExecutions createServiceUtilizationTypeListFederationExecutions() {
        return new ServiceUtilizationType.ListFederationExecutions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReportFederationExecutions }
     * 
     */
    public ServiceUtilizationType.ReportFederationExecutions createServiceUtilizationTypeReportFederationExecutions() {
        return new ServiceUtilizationType.ReportFederationExecutions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.JoinFederationExecution }
     * 
     */
    public ServiceUtilizationType.JoinFederationExecution createServiceUtilizationTypeJoinFederationExecution() {
        return new ServiceUtilizationType.JoinFederationExecution();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ResignFederationExecution }
     * 
     */
    public ServiceUtilizationType.ResignFederationExecution createServiceUtilizationTypeResignFederationExecution() {
        return new ServiceUtilizationType.ResignFederationExecution();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RegisterFederationSynchronizationPoint }
     * 
     */
    public ServiceUtilizationType.RegisterFederationSynchronizationPoint createServiceUtilizationTypeRegisterFederationSynchronizationPoint() {
        return new ServiceUtilizationType.RegisterFederationSynchronizationPoint();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ConfirmSynchronizationPointRegistration }
     * 
     */
    public ServiceUtilizationType.ConfirmSynchronizationPointRegistration createServiceUtilizationTypeConfirmSynchronizationPointRegistration() {
        return new ServiceUtilizationType.ConfirmSynchronizationPointRegistration();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AnnounceSynchronizationPoint }
     * 
     */
    public ServiceUtilizationType.AnnounceSynchronizationPoint createServiceUtilizationTypeAnnounceSynchronizationPoint() {
        return new ServiceUtilizationType.AnnounceSynchronizationPoint();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SynchronizationPointAchieved }
     * 
     */
    public ServiceUtilizationType.SynchronizationPointAchieved createServiceUtilizationTypeSynchronizationPointAchieved() {
        return new ServiceUtilizationType.SynchronizationPointAchieved();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederationSynchronized }
     * 
     */
    public ServiceUtilizationType.FederationSynchronized createServiceUtilizationTypeFederationSynchronized() {
        return new ServiceUtilizationType.FederationSynchronized();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestFederationSave }
     * 
     */
    public ServiceUtilizationType.RequestFederationSave createServiceUtilizationTypeRequestFederationSave() {
        return new ServiceUtilizationType.RequestFederationSave();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.InitiateFederateSave }
     * 
     */
    public ServiceUtilizationType.InitiateFederateSave createServiceUtilizationTypeInitiateFederateSave() {
        return new ServiceUtilizationType.InitiateFederateSave();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederateSaveBegun }
     * 
     */
    public ServiceUtilizationType.FederateSaveBegun createServiceUtilizationTypeFederateSaveBegun() {
        return new ServiceUtilizationType.FederateSaveBegun();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederateSaveComplete }
     * 
     */
    public ServiceUtilizationType.FederateSaveComplete createServiceUtilizationTypeFederateSaveComplete() {
        return new ServiceUtilizationType.FederateSaveComplete();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederationSaved }
     * 
     */
    public ServiceUtilizationType.FederationSaved createServiceUtilizationTypeFederationSaved() {
        return new ServiceUtilizationType.FederationSaved();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AbortFederationSave }
     * 
     */
    public ServiceUtilizationType.AbortFederationSave createServiceUtilizationTypeAbortFederationSave() {
        return new ServiceUtilizationType.AbortFederationSave();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryFederationSaveStatus }
     * 
     */
    public ServiceUtilizationType.QueryFederationSaveStatus createServiceUtilizationTypeQueryFederationSaveStatus() {
        return new ServiceUtilizationType.QueryFederationSaveStatus();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederationSaveStatusResponse }
     * 
     */
    public ServiceUtilizationType.FederationSaveStatusResponse createServiceUtilizationTypeFederationSaveStatusResponse() {
        return new ServiceUtilizationType.FederationSaveStatusResponse();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestFederationRestore }
     * 
     */
    public ServiceUtilizationType.RequestFederationRestore createServiceUtilizationTypeRequestFederationRestore() {
        return new ServiceUtilizationType.RequestFederationRestore();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ConfirmFederationRestorationRequest }
     * 
     */
    public ServiceUtilizationType.ConfirmFederationRestorationRequest createServiceUtilizationTypeConfirmFederationRestorationRequest() {
        return new ServiceUtilizationType.ConfirmFederationRestorationRequest();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederationRestoreBegun }
     * 
     */
    public ServiceUtilizationType.FederationRestoreBegun createServiceUtilizationTypeFederationRestoreBegun() {
        return new ServiceUtilizationType.FederationRestoreBegun();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.InitiateFederateRestore }
     * 
     */
    public ServiceUtilizationType.InitiateFederateRestore createServiceUtilizationTypeInitiateFederateRestore() {
        return new ServiceUtilizationType.InitiateFederateRestore();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederateRestoreComplete }
     * 
     */
    public ServiceUtilizationType.FederateRestoreComplete createServiceUtilizationTypeFederateRestoreComplete() {
        return new ServiceUtilizationType.FederateRestoreComplete();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederationRestored }
     * 
     */
    public ServiceUtilizationType.FederationRestored createServiceUtilizationTypeFederationRestored() {
        return new ServiceUtilizationType.FederationRestored();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AbortFederationRestore }
     * 
     */
    public ServiceUtilizationType.AbortFederationRestore createServiceUtilizationTypeAbortFederationRestore() {
        return new ServiceUtilizationType.AbortFederationRestore();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryFederationRestoreStatus }
     * 
     */
    public ServiceUtilizationType.QueryFederationRestoreStatus createServiceUtilizationTypeQueryFederationRestoreStatus() {
        return new ServiceUtilizationType.QueryFederationRestoreStatus();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FederationRestoreStatusResponse }
     * 
     */
    public ServiceUtilizationType.FederationRestoreStatusResponse createServiceUtilizationTypeFederationRestoreStatusResponse() {
        return new ServiceUtilizationType.FederationRestoreStatusResponse();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.PublishObjectClassAttributes }
     * 
     */
    public ServiceUtilizationType.PublishObjectClassAttributes createServiceUtilizationTypePublishObjectClassAttributes() {
        return new ServiceUtilizationType.PublishObjectClassAttributes();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UnpublishObjectClassAttributes }
     * 
     */
    public ServiceUtilizationType.UnpublishObjectClassAttributes createServiceUtilizationTypeUnpublishObjectClassAttributes() {
        return new ServiceUtilizationType.UnpublishObjectClassAttributes();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.PublishInteractionClass }
     * 
     */
    public ServiceUtilizationType.PublishInteractionClass createServiceUtilizationTypePublishInteractionClass() {
        return new ServiceUtilizationType.PublishInteractionClass();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UnpublishInteractionClass }
     * 
     */
    public ServiceUtilizationType.UnpublishInteractionClass createServiceUtilizationTypeUnpublishInteractionClass() {
        return new ServiceUtilizationType.UnpublishInteractionClass();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SubscribeObjectClassAttributes }
     * 
     */
    public ServiceUtilizationType.SubscribeObjectClassAttributes createServiceUtilizationTypeSubscribeObjectClassAttributes() {
        return new ServiceUtilizationType.SubscribeObjectClassAttributes();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UnsubscribeObjectClassAttributes }
     * 
     */
    public ServiceUtilizationType.UnsubscribeObjectClassAttributes createServiceUtilizationTypeUnsubscribeObjectClassAttributes() {
        return new ServiceUtilizationType.UnsubscribeObjectClassAttributes();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SubscribeInteractionClass }
     * 
     */
    public ServiceUtilizationType.SubscribeInteractionClass createServiceUtilizationTypeSubscribeInteractionClass() {
        return new ServiceUtilizationType.SubscribeInteractionClass();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UnsubscribeInteractionClass }
     * 
     */
    public ServiceUtilizationType.UnsubscribeInteractionClass createServiceUtilizationTypeUnsubscribeInteractionClass() {
        return new ServiceUtilizationType.UnsubscribeInteractionClass();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.StartRegistrationForObjectClass }
     * 
     */
    public ServiceUtilizationType.StartRegistrationForObjectClass createServiceUtilizationTypeStartRegistrationForObjectClass() {
        return new ServiceUtilizationType.StartRegistrationForObjectClass();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.StopRegistrationForObjectClass }
     * 
     */
    public ServiceUtilizationType.StopRegistrationForObjectClass createServiceUtilizationTypeStopRegistrationForObjectClass() {
        return new ServiceUtilizationType.StopRegistrationForObjectClass();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TurnInteractionsOn }
     * 
     */
    public ServiceUtilizationType.TurnInteractionsOn createServiceUtilizationTypeTurnInteractionsOn() {
        return new ServiceUtilizationType.TurnInteractionsOn();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TurnInteractionsOff }
     * 
     */
    public ServiceUtilizationType.TurnInteractionsOff createServiceUtilizationTypeTurnInteractionsOff() {
        return new ServiceUtilizationType.TurnInteractionsOff();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReserveObjectInstanceName }
     * 
     */
    public ServiceUtilizationType.ReserveObjectInstanceName createServiceUtilizationTypeReserveObjectInstanceName() {
        return new ServiceUtilizationType.ReserveObjectInstanceName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ObjectInstanceNameReserved }
     * 
     */
    public ServiceUtilizationType.ObjectInstanceNameReserved createServiceUtilizationTypeObjectInstanceNameReserved() {
        return new ServiceUtilizationType.ObjectInstanceNameReserved();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReleaseObjectInstanceName }
     * 
     */
    public ServiceUtilizationType.ReleaseObjectInstanceName createServiceUtilizationTypeReleaseObjectInstanceName() {
        return new ServiceUtilizationType.ReleaseObjectInstanceName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReserveMultipleObjectInstanceNames }
     * 
     */
    public ServiceUtilizationType.ReserveMultipleObjectInstanceNames createServiceUtilizationTypeReserveMultipleObjectInstanceNames() {
        return new ServiceUtilizationType.ReserveMultipleObjectInstanceNames();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.MultipleObjectInstanceNamesReserved }
     * 
     */
    public ServiceUtilizationType.MultipleObjectInstanceNamesReserved createServiceUtilizationTypeMultipleObjectInstanceNamesReserved() {
        return new ServiceUtilizationType.MultipleObjectInstanceNamesReserved();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReleaseMultipleObjectInstanceNames }
     * 
     */
    public ServiceUtilizationType.ReleaseMultipleObjectInstanceNames createServiceUtilizationTypeReleaseMultipleObjectInstanceNames() {
        return new ServiceUtilizationType.ReleaseMultipleObjectInstanceNames();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RegisterObjectInstance }
     * 
     */
    public ServiceUtilizationType.RegisterObjectInstance createServiceUtilizationTypeRegisterObjectInstance() {
        return new ServiceUtilizationType.RegisterObjectInstance();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DiscoverObjectInstance }
     * 
     */
    public ServiceUtilizationType.DiscoverObjectInstance createServiceUtilizationTypeDiscoverObjectInstance() {
        return new ServiceUtilizationType.DiscoverObjectInstance();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UpdateAttributeValues }
     * 
     */
    public ServiceUtilizationType.UpdateAttributeValues createServiceUtilizationTypeUpdateAttributeValues() {
        return new ServiceUtilizationType.UpdateAttributeValues();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReflectAttributeValues }
     * 
     */
    public ServiceUtilizationType.ReflectAttributeValues createServiceUtilizationTypeReflectAttributeValues() {
        return new ServiceUtilizationType.ReflectAttributeValues();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SendInteraction }
     * 
     */
    public ServiceUtilizationType.SendInteraction createServiceUtilizationTypeSendInteraction() {
        return new ServiceUtilizationType.SendInteraction();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReceiveInteraction }
     * 
     */
    public ServiceUtilizationType.ReceiveInteraction createServiceUtilizationTypeReceiveInteraction() {
        return new ServiceUtilizationType.ReceiveInteraction();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DeleteObjectInstance }
     * 
     */
    public ServiceUtilizationType.DeleteObjectInstance createServiceUtilizationTypeDeleteObjectInstance() {
        return new ServiceUtilizationType.DeleteObjectInstance();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.Removeobjectinstance }
     * 
     */
    public ServiceUtilizationType.Removeobjectinstance createServiceUtilizationTypeRemoveobjectinstance() {
        return new ServiceUtilizationType.Removeobjectinstance();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.LocalDeleteObjectInstance }
     * 
     */
    public ServiceUtilizationType.LocalDeleteObjectInstance createServiceUtilizationTypeLocalDeleteObjectInstance() {
        return new ServiceUtilizationType.LocalDeleteObjectInstance();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AttributesInScope }
     * 
     */
    public ServiceUtilizationType.AttributesInScope createServiceUtilizationTypeAttributesInScope() {
        return new ServiceUtilizationType.AttributesInScope();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AttributesOutOfScope }
     * 
     */
    public ServiceUtilizationType.AttributesOutOfScope createServiceUtilizationTypeAttributesOutOfScope() {
        return new ServiceUtilizationType.AttributesOutOfScope();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestAttributeValueUpdate }
     * 
     */
    public ServiceUtilizationType.RequestAttributeValueUpdate createServiceUtilizationTypeRequestAttributeValueUpdate() {
        return new ServiceUtilizationType.RequestAttributeValueUpdate();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ProvideAttributeValueUpdate }
     * 
     */
    public ServiceUtilizationType.ProvideAttributeValueUpdate createServiceUtilizationTypeProvideAttributeValueUpdate() {
        return new ServiceUtilizationType.ProvideAttributeValueUpdate();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TurnUpdatesOnForObjectInstance }
     * 
     */
    public ServiceUtilizationType.TurnUpdatesOnForObjectInstance createServiceUtilizationTypeTurnUpdatesOnForObjectInstance() {
        return new ServiceUtilizationType.TurnUpdatesOnForObjectInstance();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TurnUpdatesOffForObjectInstance }
     * 
     */
    public ServiceUtilizationType.TurnUpdatesOffForObjectInstance createServiceUtilizationTypeTurnUpdatesOffForObjectInstance() {
        return new ServiceUtilizationType.TurnUpdatesOffForObjectInstance();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestAttributeTransportationTypeChange }
     * 
     */
    public ServiceUtilizationType.RequestAttributeTransportationTypeChange createServiceUtilizationTypeRequestAttributeTransportationTypeChange() {
        return new ServiceUtilizationType.RequestAttributeTransportationTypeChange();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ConfirmAttributeTransportationTypeChange }
     * 
     */
    public ServiceUtilizationType.ConfirmAttributeTransportationTypeChange createServiceUtilizationTypeConfirmAttributeTransportationTypeChange() {
        return new ServiceUtilizationType.ConfirmAttributeTransportationTypeChange();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryAttributeTransportationType }
     * 
     */
    public ServiceUtilizationType.QueryAttributeTransportationType createServiceUtilizationTypeQueryAttributeTransportationType() {
        return new ServiceUtilizationType.QueryAttributeTransportationType();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReportAttributeTransportationType }
     * 
     */
    public ServiceUtilizationType.ReportAttributeTransportationType createServiceUtilizationTypeReportAttributeTransportationType() {
        return new ServiceUtilizationType.ReportAttributeTransportationType();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestInteractionTransportationTypeChange }
     * 
     */
    public ServiceUtilizationType.RequestInteractionTransportationTypeChange createServiceUtilizationTypeRequestInteractionTransportationTypeChange() {
        return new ServiceUtilizationType.RequestInteractionTransportationTypeChange();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ConfirmInteractionTransportationTypeChange }
     * 
     */
    public ServiceUtilizationType.ConfirmInteractionTransportationTypeChange createServiceUtilizationTypeConfirmInteractionTransportationTypeChange() {
        return new ServiceUtilizationType.ConfirmInteractionTransportationTypeChange();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryInteractionTransportationType }
     * 
     */
    public ServiceUtilizationType.QueryInteractionTransportationType createServiceUtilizationTypeQueryInteractionTransportationType() {
        return new ServiceUtilizationType.QueryInteractionTransportationType();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ReportInteractionTransportationType }
     * 
     */
    public ServiceUtilizationType.ReportInteractionTransportationType createServiceUtilizationTypeReportInteractionTransportationType() {
        return new ServiceUtilizationType.ReportInteractionTransportationType();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UnconditionalAttributeOwnershipDivestiture }
     * 
     */
    public ServiceUtilizationType.UnconditionalAttributeOwnershipDivestiture createServiceUtilizationTypeUnconditionalAttributeOwnershipDivestiture() {
        return new ServiceUtilizationType.UnconditionalAttributeOwnershipDivestiture();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.NegotiatedAttributeOwnershipDivestiture }
     * 
     */
    public ServiceUtilizationType.NegotiatedAttributeOwnershipDivestiture createServiceUtilizationTypeNegotiatedAttributeOwnershipDivestiture() {
        return new ServiceUtilizationType.NegotiatedAttributeOwnershipDivestiture();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestAttributeOwnershipAssumption }
     * 
     */
    public ServiceUtilizationType.RequestAttributeOwnershipAssumption createServiceUtilizationTypeRequestAttributeOwnershipAssumption() {
        return new ServiceUtilizationType.RequestAttributeOwnershipAssumption();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestDivestitureConfirmation }
     * 
     */
    public ServiceUtilizationType.RequestDivestitureConfirmation createServiceUtilizationTypeRequestDivestitureConfirmation() {
        return new ServiceUtilizationType.RequestDivestitureConfirmation();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ConfirmDivestiture }
     * 
     */
    public ServiceUtilizationType.ConfirmDivestiture createServiceUtilizationTypeConfirmDivestiture() {
        return new ServiceUtilizationType.ConfirmDivestiture();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AttributeOwnershipAcquisitionNotification }
     * 
     */
    public ServiceUtilizationType.AttributeOwnershipAcquisitionNotification createServiceUtilizationTypeAttributeOwnershipAcquisitionNotification() {
        return new ServiceUtilizationType.AttributeOwnershipAcquisitionNotification();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AttributeOwnershipAcquisition }
     * 
     */
    public ServiceUtilizationType.AttributeOwnershipAcquisition createServiceUtilizationTypeAttributeOwnershipAcquisition() {
        return new ServiceUtilizationType.AttributeOwnershipAcquisition();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AttributeOwnershipAcquisitionIfAvailable }
     * 
     */
    public ServiceUtilizationType.AttributeOwnershipAcquisitionIfAvailable createServiceUtilizationTypeAttributeOwnershipAcquisitionIfAvailable() {
        return new ServiceUtilizationType.AttributeOwnershipAcquisitionIfAvailable();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AttributeOwnershipUnavailable }
     * 
     */
    public ServiceUtilizationType.AttributeOwnershipUnavailable createServiceUtilizationTypeAttributeOwnershipUnavailable() {
        return new ServiceUtilizationType.AttributeOwnershipUnavailable();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestAttributeOwnershipRelease }
     * 
     */
    public ServiceUtilizationType.RequestAttributeOwnershipRelease createServiceUtilizationTypeRequestAttributeOwnershipRelease() {
        return new ServiceUtilizationType.RequestAttributeOwnershipRelease();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AttributeOwnershipReleaseDenied }
     * 
     */
    public ServiceUtilizationType.AttributeOwnershipReleaseDenied createServiceUtilizationTypeAttributeOwnershipReleaseDenied() {
        return new ServiceUtilizationType.AttributeOwnershipReleaseDenied();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AttributeOwnershipDivestitureIfWanted }
     * 
     */
    public ServiceUtilizationType.AttributeOwnershipDivestitureIfWanted createServiceUtilizationTypeAttributeOwnershipDivestitureIfWanted() {
        return new ServiceUtilizationType.AttributeOwnershipDivestitureIfWanted();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.CancelNegotiatedAttributeOwnershipDivestiture }
     * 
     */
    public ServiceUtilizationType.CancelNegotiatedAttributeOwnershipDivestiture createServiceUtilizationTypeCancelNegotiatedAttributeOwnershipDivestiture() {
        return new ServiceUtilizationType.CancelNegotiatedAttributeOwnershipDivestiture();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.CancelAttributeOwnershipAcquisition }
     * 
     */
    public ServiceUtilizationType.CancelAttributeOwnershipAcquisition createServiceUtilizationTypeCancelAttributeOwnershipAcquisition() {
        return new ServiceUtilizationType.CancelAttributeOwnershipAcquisition();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ConfirmAttributeOwnershipAcquisitionCancellation }
     * 
     */
    public ServiceUtilizationType.ConfirmAttributeOwnershipAcquisitionCancellation createServiceUtilizationTypeConfirmAttributeOwnershipAcquisitionCancellation() {
        return new ServiceUtilizationType.ConfirmAttributeOwnershipAcquisitionCancellation();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryAttributeOwnership }
     * 
     */
    public ServiceUtilizationType.QueryAttributeOwnership createServiceUtilizationTypeQueryAttributeOwnership() {
        return new ServiceUtilizationType.QueryAttributeOwnership();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.InformAttributeOwnership }
     * 
     */
    public ServiceUtilizationType.InformAttributeOwnership createServiceUtilizationTypeInformAttributeOwnership() {
        return new ServiceUtilizationType.InformAttributeOwnership();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.IsAttributeOwnedByFederate }
     * 
     */
    public ServiceUtilizationType.IsAttributeOwnedByFederate createServiceUtilizationTypeIsAttributeOwnedByFederate() {
        return new ServiceUtilizationType.IsAttributeOwnedByFederate();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EnableTimeRegulation }
     * 
     */
    public ServiceUtilizationType.EnableTimeRegulation createServiceUtilizationTypeEnableTimeRegulation() {
        return new ServiceUtilizationType.EnableTimeRegulation();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TimeRegulationEnabled }
     * 
     */
    public ServiceUtilizationType.TimeRegulationEnabled createServiceUtilizationTypeTimeRegulationEnabled() {
        return new ServiceUtilizationType.TimeRegulationEnabled();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DisableTimeRegulation }
     * 
     */
    public ServiceUtilizationType.DisableTimeRegulation createServiceUtilizationTypeDisableTimeRegulation() {
        return new ServiceUtilizationType.DisableTimeRegulation();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EnableTimeConstrained }
     * 
     */
    public ServiceUtilizationType.EnableTimeConstrained createServiceUtilizationTypeEnableTimeConstrained() {
        return new ServiceUtilizationType.EnableTimeConstrained();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TimeConstrainedEnabled }
     * 
     */
    public ServiceUtilizationType.TimeConstrainedEnabled createServiceUtilizationTypeTimeConstrainedEnabled() {
        return new ServiceUtilizationType.TimeConstrainedEnabled();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DisableTimeConstrained }
     * 
     */
    public ServiceUtilizationType.DisableTimeConstrained createServiceUtilizationTypeDisableTimeConstrained() {
        return new ServiceUtilizationType.DisableTimeConstrained();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TimeAdvanceRequest }
     * 
     */
    public ServiceUtilizationType.TimeAdvanceRequest createServiceUtilizationTypeTimeAdvanceRequest() {
        return new ServiceUtilizationType.TimeAdvanceRequest();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TimeAdvanceRequestAvailable }
     * 
     */
    public ServiceUtilizationType.TimeAdvanceRequestAvailable createServiceUtilizationTypeTimeAdvanceRequestAvailable() {
        return new ServiceUtilizationType.TimeAdvanceRequestAvailable();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.NextMessageRequest }
     * 
     */
    public ServiceUtilizationType.NextMessageRequest createServiceUtilizationTypeNextMessageRequest() {
        return new ServiceUtilizationType.NextMessageRequest();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.NextMessageRequestAvailable }
     * 
     */
    public ServiceUtilizationType.NextMessageRequestAvailable createServiceUtilizationTypeNextMessageRequestAvailable() {
        return new ServiceUtilizationType.NextMessageRequestAvailable();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.FlushQueueRequest }
     * 
     */
    public ServiceUtilizationType.FlushQueueRequest createServiceUtilizationTypeFlushQueueRequest() {
        return new ServiceUtilizationType.FlushQueueRequest();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.TimeAdvanceGrant }
     * 
     */
    public ServiceUtilizationType.TimeAdvanceGrant createServiceUtilizationTypeTimeAdvanceGrant() {
        return new ServiceUtilizationType.TimeAdvanceGrant();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EnableAsynchronousDelivery }
     * 
     */
    public ServiceUtilizationType.EnableAsynchronousDelivery createServiceUtilizationTypeEnableAsynchronousDelivery() {
        return new ServiceUtilizationType.EnableAsynchronousDelivery();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DisableAsynchronousDelivery }
     * 
     */
    public ServiceUtilizationType.DisableAsynchronousDelivery createServiceUtilizationTypeDisableAsynchronousDelivery() {
        return new ServiceUtilizationType.DisableAsynchronousDelivery();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryGALT }
     * 
     */
    public ServiceUtilizationType.QueryGALT createServiceUtilizationTypeQueryGALT() {
        return new ServiceUtilizationType.QueryGALT();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryLogicalTime }
     * 
     */
    public ServiceUtilizationType.QueryLogicalTime createServiceUtilizationTypeQueryLogicalTime() {
        return new ServiceUtilizationType.QueryLogicalTime();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryLITS }
     * 
     */
    public ServiceUtilizationType.QueryLITS createServiceUtilizationTypeQueryLITS() {
        return new ServiceUtilizationType.QueryLITS();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ModifyLookahead }
     * 
     */
    public ServiceUtilizationType.ModifyLookahead createServiceUtilizationTypeModifyLookahead() {
        return new ServiceUtilizationType.ModifyLookahead();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.QueryLookahead }
     * 
     */
    public ServiceUtilizationType.QueryLookahead createServiceUtilizationTypeQueryLookahead() {
        return new ServiceUtilizationType.QueryLookahead();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.Retract }
     * 
     */
    public ServiceUtilizationType.Retract createServiceUtilizationTypeRetract() {
        return new ServiceUtilizationType.Retract();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestRetraction }
     * 
     */
    public ServiceUtilizationType.RequestRetraction createServiceUtilizationTypeRequestRetraction() {
        return new ServiceUtilizationType.RequestRetraction();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ChangeAttributeOrderType }
     * 
     */
    public ServiceUtilizationType.ChangeAttributeOrderType createServiceUtilizationTypeChangeAttributeOrderType() {
        return new ServiceUtilizationType.ChangeAttributeOrderType();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.ChangeInteractionOrderType }
     * 
     */
    public ServiceUtilizationType.ChangeInteractionOrderType createServiceUtilizationTypeChangeInteractionOrderType() {
        return new ServiceUtilizationType.ChangeInteractionOrderType();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.CreateRegion }
     * 
     */
    public ServiceUtilizationType.CreateRegion createServiceUtilizationTypeCreateRegion() {
        return new ServiceUtilizationType.CreateRegion();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.CommitRegionModifications }
     * 
     */
    public ServiceUtilizationType.CommitRegionModifications createServiceUtilizationTypeCommitRegionModifications() {
        return new ServiceUtilizationType.CommitRegionModifications();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DeleteRegion }
     * 
     */
    public ServiceUtilizationType.DeleteRegion createServiceUtilizationTypeDeleteRegion() {
        return new ServiceUtilizationType.DeleteRegion();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RegisterObjectInstanceWithRegions }
     * 
     */
    public ServiceUtilizationType.RegisterObjectInstanceWithRegions createServiceUtilizationTypeRegisterObjectInstanceWithRegions() {
        return new ServiceUtilizationType.RegisterObjectInstanceWithRegions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.AssociateRegionsForUpdates }
     * 
     */
    public ServiceUtilizationType.AssociateRegionsForUpdates createServiceUtilizationTypeAssociateRegionsForUpdates() {
        return new ServiceUtilizationType.AssociateRegionsForUpdates();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UnassociateRegionsForUpdates }
     * 
     */
    public ServiceUtilizationType.UnassociateRegionsForUpdates createServiceUtilizationTypeUnassociateRegionsForUpdates() {
        return new ServiceUtilizationType.UnassociateRegionsForUpdates();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SubscribeObjectClassAttributesWithRegions }
     * 
     */
    public ServiceUtilizationType.SubscribeObjectClassAttributesWithRegions createServiceUtilizationTypeSubscribeObjectClassAttributesWithRegions() {
        return new ServiceUtilizationType.SubscribeObjectClassAttributesWithRegions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UnsubscribeObjectClassAttributesWithRegions }
     * 
     */
    public ServiceUtilizationType.UnsubscribeObjectClassAttributesWithRegions createServiceUtilizationTypeUnsubscribeObjectClassAttributesWithRegions() {
        return new ServiceUtilizationType.UnsubscribeObjectClassAttributesWithRegions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SubscribeInteractionClassWithRegions }
     * 
     */
    public ServiceUtilizationType.SubscribeInteractionClassWithRegions createServiceUtilizationTypeSubscribeInteractionClassWithRegions() {
        return new ServiceUtilizationType.SubscribeInteractionClassWithRegions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.UnsubscribeInteractionClassWithRegions }
     * 
     */
    public ServiceUtilizationType.UnsubscribeInteractionClassWithRegions createServiceUtilizationTypeUnsubscribeInteractionClassWithRegions() {
        return new ServiceUtilizationType.UnsubscribeInteractionClassWithRegions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SendInteractionWithRegions }
     * 
     */
    public ServiceUtilizationType.SendInteractionWithRegions createServiceUtilizationTypeSendInteractionWithRegions() {
        return new ServiceUtilizationType.SendInteractionWithRegions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.RequestAttributeValueUpdateWithRegions }
     * 
     */
    public ServiceUtilizationType.RequestAttributeValueUpdateWithRegions createServiceUtilizationTypeRequestAttributeValueUpdateWithRegions() {
        return new ServiceUtilizationType.RequestAttributeValueUpdateWithRegions();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetAutomaticResignDirective }
     * 
     */
    public ServiceUtilizationType.GetAutomaticResignDirective createServiceUtilizationTypeGetAutomaticResignDirective() {
        return new ServiceUtilizationType.GetAutomaticResignDirective();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SetAutomaticResignDirective }
     * 
     */
    public ServiceUtilizationType.SetAutomaticResignDirective createServiceUtilizationTypeSetAutomaticResignDirective() {
        return new ServiceUtilizationType.SetAutomaticResignDirective();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetFederateHandle }
     * 
     */
    public ServiceUtilizationType.GetFederateHandle createServiceUtilizationTypeGetFederateHandle() {
        return new ServiceUtilizationType.GetFederateHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetFederateName }
     * 
     */
    public ServiceUtilizationType.GetFederateName createServiceUtilizationTypeGetFederateName() {
        return new ServiceUtilizationType.GetFederateName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetObjectClassHandle }
     * 
     */
    public ServiceUtilizationType.GetObjectClassHandle createServiceUtilizationTypeGetObjectClassHandle() {
        return new ServiceUtilizationType.GetObjectClassHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetObjectClassName }
     * 
     */
    public ServiceUtilizationType.GetObjectClassName createServiceUtilizationTypeGetObjectClassName() {
        return new ServiceUtilizationType.GetObjectClassName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetKnownObjectClassHandle }
     * 
     */
    public ServiceUtilizationType.GetKnownObjectClassHandle createServiceUtilizationTypeGetKnownObjectClassHandle() {
        return new ServiceUtilizationType.GetKnownObjectClassHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetObjectInstanceHandle }
     * 
     */
    public ServiceUtilizationType.GetObjectInstanceHandle createServiceUtilizationTypeGetObjectInstanceHandle() {
        return new ServiceUtilizationType.GetObjectInstanceHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetObjectInstanceName }
     * 
     */
    public ServiceUtilizationType.GetObjectInstanceName createServiceUtilizationTypeGetObjectInstanceName() {
        return new ServiceUtilizationType.GetObjectInstanceName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetAttributeHandle }
     * 
     */
    public ServiceUtilizationType.GetAttributeHandle createServiceUtilizationTypeGetAttributeHandle() {
        return new ServiceUtilizationType.GetAttributeHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetAttributeName }
     * 
     */
    public ServiceUtilizationType.GetAttributeName createServiceUtilizationTypeGetAttributeName() {
        return new ServiceUtilizationType.GetAttributeName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetUpdateRateValue }
     * 
     */
    public ServiceUtilizationType.GetUpdateRateValue createServiceUtilizationTypeGetUpdateRateValue() {
        return new ServiceUtilizationType.GetUpdateRateValue();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetUpdateRateValueForAttribute }
     * 
     */
    public ServiceUtilizationType.GetUpdateRateValueForAttribute createServiceUtilizationTypeGetUpdateRateValueForAttribute() {
        return new ServiceUtilizationType.GetUpdateRateValueForAttribute();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetInteractionClassHandle }
     * 
     */
    public ServiceUtilizationType.GetInteractionClassHandle createServiceUtilizationTypeGetInteractionClassHandle() {
        return new ServiceUtilizationType.GetInteractionClassHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetInteractionClassName }
     * 
     */
    public ServiceUtilizationType.GetInteractionClassName createServiceUtilizationTypeGetInteractionClassName() {
        return new ServiceUtilizationType.GetInteractionClassName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetParameterHandle }
     * 
     */
    public ServiceUtilizationType.GetParameterHandle createServiceUtilizationTypeGetParameterHandle() {
        return new ServiceUtilizationType.GetParameterHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetParameterName }
     * 
     */
    public ServiceUtilizationType.GetParameterName createServiceUtilizationTypeGetParameterName() {
        return new ServiceUtilizationType.GetParameterName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetOrderType }
     * 
     */
    public ServiceUtilizationType.GetOrderType createServiceUtilizationTypeGetOrderType() {
        return new ServiceUtilizationType.GetOrderType();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetOrderName }
     * 
     */
    public ServiceUtilizationType.GetOrderName createServiceUtilizationTypeGetOrderName() {
        return new ServiceUtilizationType.GetOrderName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetTransportationTypeHandle }
     * 
     */
    public ServiceUtilizationType.GetTransportationTypeHandle createServiceUtilizationTypeGetTransportationTypeHandle() {
        return new ServiceUtilizationType.GetTransportationTypeHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetTransportationTypeName }
     * 
     */
    public ServiceUtilizationType.GetTransportationTypeName createServiceUtilizationTypeGetTransportationTypeName() {
        return new ServiceUtilizationType.GetTransportationTypeName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetAvailableDimensionsForClassAttribute }
     * 
     */
    public ServiceUtilizationType.GetAvailableDimensionsForClassAttribute createServiceUtilizationTypeGetAvailableDimensionsForClassAttribute() {
        return new ServiceUtilizationType.GetAvailableDimensionsForClassAttribute();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetAvailableDimensionsForInteractionClass }
     * 
     */
    public ServiceUtilizationType.GetAvailableDimensionsForInteractionClass createServiceUtilizationTypeGetAvailableDimensionsForInteractionClass() {
        return new ServiceUtilizationType.GetAvailableDimensionsForInteractionClass();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetDimensionHandle }
     * 
     */
    public ServiceUtilizationType.GetDimensionHandle createServiceUtilizationTypeGetDimensionHandle() {
        return new ServiceUtilizationType.GetDimensionHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetDimensionName }
     * 
     */
    public ServiceUtilizationType.GetDimensionName createServiceUtilizationTypeGetDimensionName() {
        return new ServiceUtilizationType.GetDimensionName();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetDimensionUpperBound }
     * 
     */
    public ServiceUtilizationType.GetDimensionUpperBound createServiceUtilizationTypeGetDimensionUpperBound() {
        return new ServiceUtilizationType.GetDimensionUpperBound();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetDimensionHandleSet }
     * 
     */
    public ServiceUtilizationType.GetDimensionHandleSet createServiceUtilizationTypeGetDimensionHandleSet() {
        return new ServiceUtilizationType.GetDimensionHandleSet();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.GetRangeBounds }
     * 
     */
    public ServiceUtilizationType.GetRangeBounds createServiceUtilizationTypeGetRangeBounds() {
        return new ServiceUtilizationType.GetRangeBounds();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.SetRangeBounds }
     * 
     */
    public ServiceUtilizationType.SetRangeBounds createServiceUtilizationTypeSetRangeBounds() {
        return new ServiceUtilizationType.SetRangeBounds();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.NormalizeFederateHandle }
     * 
     */
    public ServiceUtilizationType.NormalizeFederateHandle createServiceUtilizationTypeNormalizeFederateHandle() {
        return new ServiceUtilizationType.NormalizeFederateHandle();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.NormalizeServiceGroup }
     * 
     */
    public ServiceUtilizationType.NormalizeServiceGroup createServiceUtilizationTypeNormalizeServiceGroup() {
        return new ServiceUtilizationType.NormalizeServiceGroup();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EnableObjectClassRelevanceAdvisorySwitch }
     * 
     */
    public ServiceUtilizationType.EnableObjectClassRelevanceAdvisorySwitch createServiceUtilizationTypeEnableObjectClassRelevanceAdvisorySwitch() {
        return new ServiceUtilizationType.EnableObjectClassRelevanceAdvisorySwitch();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DisableObjectClassRelevanceAdvisorySwitch }
     * 
     */
    public ServiceUtilizationType.DisableObjectClassRelevanceAdvisorySwitch createServiceUtilizationTypeDisableObjectClassRelevanceAdvisorySwitch() {
        return new ServiceUtilizationType.DisableObjectClassRelevanceAdvisorySwitch();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EnableAttributeRelevanceAdvisorySwitch }
     * 
     */
    public ServiceUtilizationType.EnableAttributeRelevanceAdvisorySwitch createServiceUtilizationTypeEnableAttributeRelevanceAdvisorySwitch() {
        return new ServiceUtilizationType.EnableAttributeRelevanceAdvisorySwitch();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DisableAttributeRelevanceAdvisorySwitch }
     * 
     */
    public ServiceUtilizationType.DisableAttributeRelevanceAdvisorySwitch createServiceUtilizationTypeDisableAttributeRelevanceAdvisorySwitch() {
        return new ServiceUtilizationType.DisableAttributeRelevanceAdvisorySwitch();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EnableAttributeScopeAdvisorySwitch }
     * 
     */
    public ServiceUtilizationType.EnableAttributeScopeAdvisorySwitch createServiceUtilizationTypeEnableAttributeScopeAdvisorySwitch() {
        return new ServiceUtilizationType.EnableAttributeScopeAdvisorySwitch();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DisableAttributeScopeAdvisorySwitch }
     * 
     */
    public ServiceUtilizationType.DisableAttributeScopeAdvisorySwitch createServiceUtilizationTypeDisableAttributeScopeAdvisorySwitch() {
        return new ServiceUtilizationType.DisableAttributeScopeAdvisorySwitch();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EnableInteractionRelevanceAdvisorySwitch }
     * 
     */
    public ServiceUtilizationType.EnableInteractionRelevanceAdvisorySwitch createServiceUtilizationTypeEnableInteractionRelevanceAdvisorySwitch() {
        return new ServiceUtilizationType.EnableInteractionRelevanceAdvisorySwitch();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DisableInteractionRelevanceAdvisorySwitch }
     * 
     */
    public ServiceUtilizationType.DisableInteractionRelevanceAdvisorySwitch createServiceUtilizationTypeDisableInteractionRelevanceAdvisorySwitch() {
        return new ServiceUtilizationType.DisableInteractionRelevanceAdvisorySwitch();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EvokeCallback }
     * 
     */
    public ServiceUtilizationType.EvokeCallback createServiceUtilizationTypeEvokeCallback() {
        return new ServiceUtilizationType.EvokeCallback();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EvokeMultipleCallbacks }
     * 
     */
    public ServiceUtilizationType.EvokeMultipleCallbacks createServiceUtilizationTypeEvokeMultipleCallbacks() {
        return new ServiceUtilizationType.EvokeMultipleCallbacks();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.EnableCallbacks }
     * 
     */
    public ServiceUtilizationType.EnableCallbacks createServiceUtilizationTypeEnableCallbacks() {
        return new ServiceUtilizationType.EnableCallbacks();
    }

    /**
     * Create an instance of {@link ServiceUtilizationType.DisableCallbacks }
     * 
     */
    public ServiceUtilizationType.DisableCallbacks createServiceUtilizationTypeDisableCallbacks() {
        return new ServiceUtilizationType.DisableCallbacks();
    }

    /**
     * Create an instance of {@link SimpleDataTypesType.SimpleData }
     * 
     */
    public SimpleDataTypesType.SimpleData createSimpleDataTypesTypeSimpleData() {
        return new SimpleDataTypesType.SimpleData();
    }

    /**
     * Create an instance of {@link IdReferenceType.Type }
     * 
     */
    public IdReferenceType.Type createIdReferenceTypeType() {
        return new IdReferenceType.Type();
    }

    /**
     * Create an instance of {@link IdReferenceType.Identification }
     * 
     */
    public IdReferenceType.Identification createIdReferenceTypeIdentification() {
        return new IdReferenceType.Identification();
    }

    /**
     * Create an instance of {@link BasicDataRepresentationsType.BasicData }
     * 
     */
    public BasicDataRepresentationsType.BasicData createBasicDataRepresentationsTypeBasicData() {
        return new BasicDataRepresentationsType.BasicData();
    }

    /**
     * Create an instance of {@link TransportationType.Reliable }
     * 
     */
    public TransportationType.Reliable createTransportationTypeReliable() {
        return new TransportationType.Reliable();
    }

    /**
     * Create an instance of {@link VariantRecordDataType.Alternative }
     * 
     */
    public VariantRecordDataType.Alternative createVariantRecordDataTypeAlternative() {
        return new VariantRecordDataType.Alternative();
    }

    /**
     * Create an instance of {@link NotesType.Note }
     * 
     */
    public NotesType.Note createNotesTypeNote() {
        return new NotesType.Note();
    }

    /**
     * Create an instance of {@link ModelIdentificationType.ModificationDate }
     * 
     */
    public ModelIdentificationType.ModificationDate createModelIdentificationTypeModificationDate() {
        return new ModelIdentificationType.ModificationDate();
    }

    /**
     * Create an instance of {@link ModelIdentificationType.Poc }
     * 
     */
    public ModelIdentificationType.Poc createModelIdentificationTypePoc() {
        return new ModelIdentificationType.Poc();
    }

    /**
     * Create an instance of {@link ModelIdentificationType.Glyph }
     * 
     */
    public ModelIdentificationType.Glyph createModelIdentificationTypeGlyph() {
        return new ModelIdentificationType.Glyph();
    }

    /**
     * Create an instance of {@link TransportationsType.Transportation }
     * 
     */
    public TransportationsType.Transportation createTransportationsTypeTransportation() {
        return new TransportationsType.Transportation();
    }

    /**
     * Create an instance of {@link VariantRecordDataTypesType.VariantRecordData }
     * 
     */
    public VariantRecordDataTypesType.VariantRecordData createVariantRecordDataTypesTypeVariantRecordData() {
        return new VariantRecordDataTypesType.VariantRecordData();
    }

    /**
     * Create an instance of {@link TimeType.TimeStamp }
     * 
     */
    public TimeType.TimeStamp createTimeTypeTimeStamp() {
        return new TimeType.TimeStamp();
    }

    /**
     * Create an instance of {@link TimeType.Lookahead }
     * 
     */
    public TimeType.Lookahead createTimeTypeLookahead() {
        return new TimeType.Lookahead();
    }

    /**
     * Create an instance of {@link DimensionsType.Dimension }
     * 
     */
    public DimensionsType.Dimension createDimensionsTypeDimension() {
        return new DimensionsType.Dimension();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectModelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://standards.ieee.org/IEEE1516-2010", name = "objectModel")
    public JAXBElement<ObjectModelType> createObjectModel(ObjectModelType value) {
        return new JAXBElement<ObjectModelType>(_ObjectModel_QNAME, ObjectModelType.class, null, value);
    }

}
