//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 09:06:12 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://standards.ieee.org/IEEE1516-2010", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.cmabreu.webomt.ieee1516e;
