//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 09:06:12 AM BRT 
//


package br.com.cmabreu.webomt.ieee1516e;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pocType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pocType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pocType" type="{http://standards.ieee.org/IEEE1516-2010}pocTypeType" minOccurs="0"/>
 *         &lt;element name="pocName" type="{http://standards.ieee.org/IEEE1516-2010}String" minOccurs="0"/>
 *         &lt;element name="pocOrg" type="{http://standards.ieee.org/IEEE1516-2010}String" minOccurs="0"/>
 *         &lt;element name="pocTelephone" type="{http://standards.ieee.org/IEEE1516-2010}String" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pocEmail" type="{http://standards.ieee.org/IEEE1516-2010}String" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pocType", propOrder = {
    "pocType",
    "pocName",
    "pocOrg",
    "pocTelephone",
    "pocEmail"
})
@XmlSeeAlso({
    br.com.cmabreu.webomt.ieee1516e.ModelIdentificationType.Poc.class
})
public class PocType {

    protected PocTypeType pocType;
    protected String pocName;
    protected String pocOrg;
    protected List<String> pocTelephone;
    protected List<String> pocEmail;

    /**
     * Gets the value of the pocType property.
     * 
     * @return
     *     possible object is
     *     {@link PocTypeType }
     *     
     */
    public PocTypeType getPocType() {
        return pocType;
    }

    /**
     * Sets the value of the pocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PocTypeType }
     *     
     */
    public void setPocType(PocTypeType value) {
        this.pocType = value;
    }

    /**
     * Gets the value of the pocName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPocName() {
        return pocName;
    }

    /**
     * Sets the value of the pocName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPocName(String value) {
        this.pocName = value;
    }

    /**
     * Gets the value of the pocOrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPocOrg() {
        return pocOrg;
    }

    /**
     * Sets the value of the pocOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPocOrg(String value) {
        this.pocOrg = value;
    }

    /**
     * Gets the value of the pocTelephone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pocTelephone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPocTelephone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPocTelephone() {
        if (pocTelephone == null) {
            pocTelephone = new ArrayList<String>();
        }
        return this.pocTelephone;
    }

    /**
     * Gets the value of the pocEmail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pocEmail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPocEmail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPocEmail() {
        if (pocEmail == null) {
            pocEmail = new ArrayList<String>();
        }
        return this.pocEmail;
    }

}
