//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 09:06:12 AM BRT 
//


package br.com.cmabreu.webomt.ieee1516e;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resignActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="resignActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UnconditionallyDivestAttributes"/>
 *     &lt;enumeration value="DeleteObjects"/>
 *     &lt;enumeration value="CancelPendingOwnershipAcquisitions"/>
 *     &lt;enumeration value="DeleteObjectsThenDivest"/>
 *     &lt;enumeration value="CancelThenDeleteThenDivest"/>
 *     &lt;enumeration value="NoAction"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "resignActionType")
@XmlEnum
public enum ResignActionType {

    @XmlEnumValue("UnconditionallyDivestAttributes")
    UNCONDITIONALLY_DIVEST_ATTRIBUTES("UnconditionallyDivestAttributes"),
    @XmlEnumValue("DeleteObjects")
    DELETE_OBJECTS("DeleteObjects"),
    @XmlEnumValue("CancelPendingOwnershipAcquisitions")
    CANCEL_PENDING_OWNERSHIP_ACQUISITIONS("CancelPendingOwnershipAcquisitions"),
    @XmlEnumValue("DeleteObjectsThenDivest")
    DELETE_OBJECTS_THEN_DIVEST("DeleteObjectsThenDivest"),
    @XmlEnumValue("CancelThenDeleteThenDivest")
    CANCEL_THEN_DELETE_THEN_DIVEST("CancelThenDeleteThenDivest"),
    @XmlEnumValue("NoAction")
    NO_ACTION("NoAction");
    private final java.lang.String value;

    ResignActionType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ResignActionType fromValue(java.lang.String v) {
        for (ResignActionType c: ResignActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
