//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 09:06:12 AM BRT 
//


package br.com.cmabreu.webomt.ieee1516e;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for switchesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="switchesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="autoProvide" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="conveyRegionDesignatorSets" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="conveyProducingFederate" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="attributeScopeAdvisory" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="attributeRelevanceAdvisory" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="objectClassRelevanceAdvisory" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="interactionRelevanceAdvisory" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="serviceReporting" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="exceptionReporting" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="delaySubscriptionEvaluation" type="{http://standards.ieee.org/IEEE1516-2010}switchType" minOccurs="0"/>
 *         &lt;element name="automaticResignAction" type="{http://standards.ieee.org/IEEE1516-2010}resignSwitchType" minOccurs="0"/>
 *         &lt;any namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://standards.ieee.org/IEEE1516-2010}commonAttributes"/>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "switchesType", propOrder = {
    "autoProvide",
    "conveyRegionDesignatorSets",
    "conveyProducingFederate",
    "attributeScopeAdvisory",
    "attributeRelevanceAdvisory",
    "objectClassRelevanceAdvisory",
    "interactionRelevanceAdvisory",
    "serviceReporting",
    "exceptionReporting",
    "delaySubscriptionEvaluation",
    "automaticResignAction",
    "any"
})
public class SwitchesType {

    protected SwitchType autoProvide;
    protected SwitchType conveyRegionDesignatorSets;
    protected SwitchType conveyProducingFederate;
    protected SwitchType attributeScopeAdvisory;
    protected SwitchType attributeRelevanceAdvisory;
    protected SwitchType objectClassRelevanceAdvisory;
    protected SwitchType interactionRelevanceAdvisory;
    protected SwitchType serviceReporting;
    protected SwitchType exceptionReporting;
    protected SwitchType delaySubscriptionEvaluation;
    protected ResignSwitchType automaticResignAction;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(name = "idtag")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String idtag;
    @XmlAnyAttribute
    private Map<QName, java.lang.String> otherAttributes = new HashMap<QName, java.lang.String>();

    /**
     * Gets the value of the autoProvide property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getAutoProvide() {
        return autoProvide;
    }

    /**
     * Sets the value of the autoProvide property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setAutoProvide(SwitchType value) {
        this.autoProvide = value;
    }

    /**
     * Gets the value of the conveyRegionDesignatorSets property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getConveyRegionDesignatorSets() {
        return conveyRegionDesignatorSets;
    }

    /**
     * Sets the value of the conveyRegionDesignatorSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setConveyRegionDesignatorSets(SwitchType value) {
        this.conveyRegionDesignatorSets = value;
    }

    /**
     * Gets the value of the conveyProducingFederate property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getConveyProducingFederate() {
        return conveyProducingFederate;
    }

    /**
     * Sets the value of the conveyProducingFederate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setConveyProducingFederate(SwitchType value) {
        this.conveyProducingFederate = value;
    }

    /**
     * Gets the value of the attributeScopeAdvisory property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getAttributeScopeAdvisory() {
        return attributeScopeAdvisory;
    }

    /**
     * Sets the value of the attributeScopeAdvisory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setAttributeScopeAdvisory(SwitchType value) {
        this.attributeScopeAdvisory = value;
    }

    /**
     * Gets the value of the attributeRelevanceAdvisory property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getAttributeRelevanceAdvisory() {
        return attributeRelevanceAdvisory;
    }

    /**
     * Sets the value of the attributeRelevanceAdvisory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setAttributeRelevanceAdvisory(SwitchType value) {
        this.attributeRelevanceAdvisory = value;
    }

    /**
     * Gets the value of the objectClassRelevanceAdvisory property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getObjectClassRelevanceAdvisory() {
        return objectClassRelevanceAdvisory;
    }

    /**
     * Sets the value of the objectClassRelevanceAdvisory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setObjectClassRelevanceAdvisory(SwitchType value) {
        this.objectClassRelevanceAdvisory = value;
    }

    /**
     * Gets the value of the interactionRelevanceAdvisory property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getInteractionRelevanceAdvisory() {
        return interactionRelevanceAdvisory;
    }

    /**
     * Sets the value of the interactionRelevanceAdvisory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setInteractionRelevanceAdvisory(SwitchType value) {
        this.interactionRelevanceAdvisory = value;
    }

    /**
     * Gets the value of the serviceReporting property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getServiceReporting() {
        return serviceReporting;
    }

    /**
     * Sets the value of the serviceReporting property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setServiceReporting(SwitchType value) {
        this.serviceReporting = value;
    }

    /**
     * Gets the value of the exceptionReporting property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getExceptionReporting() {
        return exceptionReporting;
    }

    /**
     * Sets the value of the exceptionReporting property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setExceptionReporting(SwitchType value) {
        this.exceptionReporting = value;
    }

    /**
     * Gets the value of the delaySubscriptionEvaluation property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchType }
     *     
     */
    public SwitchType getDelaySubscriptionEvaluation() {
        return delaySubscriptionEvaluation;
    }

    /**
     * Sets the value of the delaySubscriptionEvaluation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchType }
     *     
     */
    public void setDelaySubscriptionEvaluation(SwitchType value) {
        this.delaySubscriptionEvaluation = value;
    }

    /**
     * Gets the value of the automaticResignAction property.
     * 
     * @return
     *     possible object is
     *     {@link ResignSwitchType }
     *     
     */
    public ResignSwitchType getAutomaticResignAction() {
        return automaticResignAction;
    }

    /**
     * Sets the value of the automaticResignAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResignSwitchType }
     *     
     */
    public void setAutomaticResignAction(ResignSwitchType value) {
        this.automaticResignAction = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the idtag property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIdtag() {
        return idtag;
    }

    /**
     * Sets the value of the idtag property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIdtag(java.lang.String value) {
        this.idtag = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, java.lang.String> getOtherAttributes() {
        return otherAttributes;
    }

}
